---
- name: Include distro specific tasks
  include: "{{ ansible_os_family|lower }}.yml"

- name: Create docker group
  group:
    name: docker
    state: present

- name: Add user {{ ansible_user }} to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Enable Docker remote API
  include: remoteAPI.yml
  when: enable_remote_docker_api == true

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes