---
- name: Uninstall previous Docker versions
  apt:
    name: "{{ unnecesary_docker_packages }}"
    state: absent
  vars:
    unnecesary_docker_packages:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
  when: ansible_os_family == "Debian"

- name: Ensure necesary Docker packages are installed
  apt:
    name: "{{ docker_necesary_packages }}"
    state: latest
  vars:
    docker_necesary_packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
  when: ansible_os_family == "Debian"

- name: Add Docker official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_os_family == "Debian"

- name: Add Docker Official repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  when: ansible_os_family == "Debian"

- name: Update APT and install Docker CE
  apt:
    name: "{{ necesary_docker_packages }}"
    state: latest
    update_cache: yes
  vars:
    necesary_docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  when: ansible_os_family == "Debian"

- name: Create docker group
  group:
    name: docker
    state: present

- name: Add user {{ ansible_user }} to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes