---
- name: Ensure /etc/systemd/system/docker.service.d/ exists
  file:
    path: /etc/systemd/system/docker.service.d/
    state: directory

- name: Create /etc/systemd/system/docker.service.d/startup_options.conf
  template:
    src: templates/docker_startup_options.conf
    dest: /etc/systemd/system/docker.service.d/startup_options.conf
  when: ansible_tun0 is defined and ansible_tun0.active == true

- name: Reload and restart docker daemon
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
